"""Conventional-commit generation and validation (SPEC §5.11).

The product repo runs ``@commitlint/config-conventional`` from ``.husky/commit-msg``. That config
caps the header at 100 characters **and** every body line and every footer line at 100. The body
half is the one that is commonly missed, so ``build()`` hard-wraps rather than trusting the model
to count, and ``validate()`` checks every line rather than only the first.

An over-long subject is regenerated by dropping trailing words, never truncated: a header cut
mid-word reads as a bug in the tool that wrote it.
"""

from __future__ import annotations

import re
import textwrap
from typing import Sequence

MAX_HEADER = 100
MAX_BODY_LINE = 100

#: The conventional types accepted by ``@commitlint/config-conventional``.
TYPES: tuple[str, ...] = (
    "build",
    "chore",
    "ci",
    "docs",
    "feat",
    "fix",
    "perf",
    "refactor",
    "revert",
    "style",
    "test",
)

_HEADER_RE = re.compile(r"^(?P<type>[a-zA-Z]+)(?:\((?P<scope>[^()]*)\))?(?P<bang>!)?: (?P<subject>.*)$")


def _normalise_subject(subject: str) -> str:
    """Collapse whitespace, strip a trailing period, lower-case the first character."""
    text = " ".join((subject or "").split())
    while text.endswith("."):
        text = text[:-1].rstrip()
    if text:
        text = text[0].lower() + text[1:]
    return text


def _fit_subject(prefix_len: int, subject: str) -> str:
    """Drop trailing words until ``prefix + subject`` fits in 100 characters, keeping >= 1 word."""
    words = subject.split()
    if not words:
        return subject
    while len(words) > 1 and prefix_len + len(" ".join(words)) > MAX_HEADER:
        words.pop()
    return " ".join(words)


def _wrap_block(text: str, width: int = MAX_BODY_LINE) -> list[str]:
    """Wrap each paragraph to ``width``, preserving blank-line separation.

    Long unbroken tokens (URLs, file paths, shas) are left intact — splitting one to satisfy a
    line-length rule produces a message that is shorter and wrong.
    """
    lines: list[str] = []
    paragraphs = re.split(r"\n\s*\n", (text or "").strip())
    for index, paragraph in enumerate(paragraphs):
        collapsed = " ".join(paragraph.split())
        if not collapsed:
            continue
        if index:
            lines.append("")
        lines.extend(
            textwrap.wrap(
                collapsed,
                width=width,
                break_long_words=False,
                break_on_hyphens=False,
            )
            or [collapsed]
        )
    return lines


def build(type_: str, scope: str | None, subject: str, body: str, footers: Sequence[str]) -> str:
    """Assemble a commit message that satisfies every rule ``validate()`` checks."""
    kind = (type_ or "").strip().lower()
    scope_part = f"({scope.strip()})" if scope and scope.strip() else ""
    prefix = f"{kind}{scope_part}: "

    clean_subject = _normalise_subject(subject)
    if not clean_subject:
        clean_subject = "update"
    clean_subject = _fit_subject(len(prefix), clean_subject)

    parts: list[str] = [prefix + clean_subject]

    body_lines = _wrap_block(body)
    if body_lines:
        parts.append("\n".join(body_lines))

    footer_lines: list[str] = []
    for footer in footers or ():
        footer_lines.extend(_wrap_block(footer))
    if footer_lines:
        parts.append("\n".join(footer_lines))

    return "\n\n".join(parts)


def validate(message: str) -> list[str]:
    """Return the list of commitlint rule violations. An empty list means the message is valid."""
    problems: list[str] = []
    text = (message or "").replace("\r\n", "\n").rstrip("\n")
    if not text.strip():
        return ["message is empty"]

    lines = text.split("\n")
    header = lines[0]

    if len(header) > MAX_HEADER:
        problems.append(f"header is {len(header)} characters, over the {MAX_HEADER} limit")

    match = _HEADER_RE.match(header)
    if not match:
        problems.append("header must be '<type>(<scope>): <subject>' with a space after the colon")
    else:
        kind = match.group("type")
        subject = match.group("subject")
        if kind not in TYPES:
            problems.append(f"type '{kind}' is not one of: {', '.join(TYPES)}")
        if kind != kind.lower():
            problems.append(f"type '{kind}' must be lower-case")
        if not subject.strip():
            problems.append("subject must not be empty")
        else:
            if subject.rstrip().endswith("."):
                problems.append("subject must not end with a period")
            first = subject.strip()[0]
            if first.isalpha() and first.isupper():
                problems.append("subject must start lower-case")

    if len(lines) > 1 and lines[1].strip():
        problems.append("the header must be followed by a blank line")

    for number, line in enumerate(lines[1:], start=2):
        if len(line) > MAX_BODY_LINE:
            problems.append(
                f"line {number} is {len(line)} characters, over the {MAX_BODY_LINE} limit"
            )

    return problems
